### PR TITLE
ax: enable Receive All mode to bypass the MAC filter

### PR DESCRIPTION
**Pull request by swhite2**
The hardware MAC filter is dropping CARP MAC addresses. Enabling promiscuous mode still does not resolve this (which might indicate a firmware issue). Luckily the MAC filter can be overridden to simply pass everything.

### CODE REVIEW

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by fichtner** [comment]
@swhite2 actually do you want a test kernel?

**Comment by swhite2** [comment]
> @swhite2 actually do you want a test kernel?

Sure! I'll take a look.

**Comment by fichtner** [comment]
# opnsense-update -zkr 21.1.4_1

Happy Easter!

**Pull request merged**
