### PR TITLE
Stable/20.7

### PR DESCRIPTION
**Pull request by jdpc86**
added belkin b2b128 usb3 ethernet support, cherry pick gigabit change…
b1ea802

… from FreeBSD b17c231, re-facotred code to work with 20.7

https://github.com/freebsd/freebsd/commit/b17c2310fc3073aed1586aff8690547d5102db99

my local testing showed improvement up to 150M download speed when runing cli speedtest from OPNsense...this appears to be capped by ISP...

Would be great if this can be reviewed and possibly committed until a later FreeBSD is available in OPNsense...
Thanks!

### CODE REVIEW

**Comment by fichtner** [comment]
Two things here:

1. we will wait for the MFC to stable/12, https://github.com/freebsd/freebsd/commit/b17c2310fc is 7 days old today. I can't review this at all.
2. we do not accept PRs to the stable branches, only master

**Comment by jdpc86** [comment]
Thanks!

Created new PR against master here:

https://github.com/opnsense/src/pull/79

a quick update, my local testing appears to be going well, get up to 300m which is way more than 91m i was getting...there was a slow down on modem that appears to have cut it down to 150m...a reboot of modem appears to have fixed it...

**Comment by fichtner** [comment]
Thanks. We will stay on 12.1 kernel for 21.1 but I have no issue getting this into 21.1 or possibly 20.7.x. My only request is a proper MFC that we can raise a FreeBSD ticket against when the time comes if need be.😊

**Comment by jdpc86** [comment]
Thanks Franco!

**Pull request closed without merging**
