### PR TITLE
Provide a more useful shell

### PR DESCRIPTION
**Pull request by doktornotor**
Add OPNsense version and FQDN to shell prompt. Implements #193.

### CODE REVIEW

**Comment by fichtner** [comment]
To be frank it was intentionally left out during the fork. Maybe we can add an option and/or provide an overrideable template. At least then these changes wouldn’t get lost in the source code updates here.

**Comment by doktornotor** [comment]
LOL, OK. Would System - Access - Users (e.g. below the login shell selection) be an overkill? 

As a side note - what's going on with the .cshrc here? Also complaining about hardlinks when editing,

**Comment by fichtner** [comment]
ok great the two files are already "same same but different" so we need to template both for diminishing results but I guess there is a way to compress these into one -.-

> Would System - Access - Users (e.g. below the login shell selection) be an overkill?

How about a global switch under System: Settings: Administration? There is some shell and console glue there anyway.

> As a side note - what's going on with the .cshrc here? Also complaining about hardlinks when editing

Not sure where.. in the repo or in the system? Haven't seen this.


Cheers,
Franco

**Comment by fichtner** [comment]
As an afterthought we are going to scrub everyone's .cshrc files with this. I have no idea what modifications users have made over the years. Usually that is why we steer away from providing templating for this because it will then pin the contents and force everyone to work around in a more destructive way. ;)

**Comment by AdSchellevis** [comment]
the better question probably is which process is currently responsible for modifying root's `.cshrc` file as this sounds a bit unintentional.

**Comment by fichtner** [comment]
root's .cshrc is bootstrapped by `bin/csh/dot.cshrc` as an intentional side effect it seems. But it's a bit worse in terms of distribution:

config/23.7/base.plist.amd64:/.cshrc
config/23.7/base.plist.amd64:/etc/csh.cshrc
config/23.7/base.plist.amd64:/root/.cshrc

Looking at it /etc/csh.cshrc probably works...

**Comment by doktornotor** [comment]
> > As a side note - what's going on with the .cshrc here? Also complaining about hardlinks when editing
> 
> Not sure where.. in the repo or in the system? Haven't seen this.

In the system. Just trying to edit with `mcedit`

image

> As an afterthought we are going to scrub everyone's .cshrc files with this. I have no idea what modifications users have made over the years

Well yes. Perhaps something like a simple sed on the currently used `~/.cshrc` file is feasible, so that only this part gets touched and only when you configure it? Though, with the "reset" feature on upgrade, not sure how many customizations people have. Or, is that reset root-specific?

**Comment by fichtner** [comment]
/etc/csh.cshrc appears to be completely ignored? whew.

**Comment by AdSchellevis** [comment]
to me it sounds quite weird files in /root are being touched on upgrade (when /root does already exist), but I never looked very closely earlier to be honest.

**Comment by fichtner** [comment]
~/.cshrc appears to be hardlinked to /.cshrc indeed:

```
# ls -i /.cshrc 
290484 /.cshrc
# ls -i /root/.cshrc 
290484 /root/.cshrc
```

**Comment by fichtner** [comment]
> to me it sounds quite weird files in /root are being touched on upgrade (when /root does already exist), but I never looked very closely earlier to be honest.

It's for bootstrap use.. since you need a user for the first boot anyway. But I doubt freebsd-update does it differently.

**Comment by AdSchellevis** [comment]
for bootstrapping it's logical, upgrade not so much?

**Comment by doktornotor** [comment]
> ~/.cshrc appears to be hardlinked to /.cshrc indeed:
> 
> ```
> # ls -i /.cshrc 
> 290484 /.cshrc
> # ls -i /root/.cshrc 
> 290484 /root/.cshrc
> ```

So, what are these files doing there anyway? 

```
/.profile
/.cshrc

```
Then there's also 

```
/COPYRIGHT
/boot.config
/sys
/.probe.for.readonly
/entropy


```
 `sys` appears a broken symlink to `usr/src/sys`, I sort of understand the `COPYRIGHT` and the `entropy` seed.

**Comment by fichtner** [comment]
These are all good questions for FreeBSD. Apparently / was the home directory of root before /root was added. I don't know about the rest of the historic reasons, but also we don't really have to care too much.

**Comment by doktornotor** [comment]
Oh, those come from "vanilla" FreeBSD? Thought it's some leftovers from the install/upgrade process specific to OPNsense. Meh,..

**Comment by fichtner** [comment]
Yep, it's from FreeBSD. Also I think root shell moved to sh in FreeBSD 14.0 away from csh?

**Comment by doktornotor** [comment]
Ok, so now thinking about it... if the hardlink is gone, the `/root/.cshrc` - all those customizations would persist, no? As for `sh`, suspect the same issue otherwise with the `/.profile` hardlink, so? 

```
# ls -i /.profile ~/.profile
197688 /.profile        197688 /root/.profile

```

**Comment by fichtner** [comment]
The base update would clobber it, but that's why we have post-update hooks to rewrite templates. The hardlink itself isn't an issue I believe.

**Comment by fichtner** [comment]
We talked about this internally some more... just to be sure: is your problem related to the ~/.profile and ~/.cshrc file being overwritten by updates? Because that part can easily be fixed by opnsense-update adjustment.

**Comment by doktornotor** [comment]
> We talked about this internally some more... just to be sure: is your problem related to the ~/.profile and ~/.cshrc file being overwritten by updates? Because that part can easily be fixed by opnsense-update adjustment.

Well yes, not undoing the customizations is perfectly fine, it's one-time manual config once that behaviour is changed.

**Comment by fichtner** [comment]
https://github.com/opnsense/core/commit/927c37c1356 plus https://github.com/opnsense/update/commit/fa4f0c4cf9ab4 should fix the overwrite and spurious health audit messages due to modifications.

**Comment by doktornotor** [comment]
Cool, thanks, will see how it goes on next update. Close this PR, or keep it open meanwhile?

**Comment by fichtner** [comment]
Can close this. I don't know if 23.7.x will have another base/kernel update, but it's set for 24.1 inclusion and my local test went fine.

**Comment by doktornotor** [comment]
Ok, the modified files survived on all boxes with 23.7.11 🎉

**Comment by fichtner** [comment]
glad to hear :)

**Pull request closed without merging**
